name: MysticCore
author: QuickScythe
version: 3.5.1
description: Runs on all MysticCloud servers
api-version: 1.20
api: Spigot
main: net.mysticcloud.spigot.core.MysticCore
commands:
  update:
    description: Update a plugin in our repository.
    usage: /update <plugin>
  kick:
    description: Kicks a player
    usage: /kick <player>
  region:
    description: Region command.
    usage: /region help
  sudo:
    description: Control another player
    usage: /sudo <player> <action>
  inventory:
    usage: /inventory <inventory>
    aliases:
      - inv
      - gui
  npc:
    usage: /npc help
    description: Spawn or edit an NPC